matrix:
- name: Markdown
  aspell:
    lang: de 
  dictionary:
    encoding: utf-8
    wordlists:
    - config/.wordlist.txt
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
    comments: false
    ignores:
    - code
    - pre
  sources:
  - '_notes/*.md'
  default_encoding: utf-8
